version: "3"

services: 
  docker-minecraft-server:
    build:
      context: .
      args: 
        RAM_AMOUNT: 1G
    volumes:
      - .server:/server
    ports:
      - 25565:25565
      - 25575:25575
    container_name: ${CONTAINER_NAME}
    
volumes:
  server:
